<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Municipio;

class MunicipioSeeder extends Seeder
{
    public function run()
    {
        $municipios = [
            // ID 1: San Salvador
            ['id_departamento' => 1, 'nombre' => 'San Salvador'],
            ['id_departamento' => 1, 'nombre' => 'Aguilares'],
            ['id_departamento' => 1, 'nombre' => 'Apopa'],
            ['id_departamento' => 1, 'nombre' => 'Ayutuxtepeque'],
            ['id_departamento' => 1, 'nombre' => 'Cuscatancingo'],
            ['id_departamento' => 1, 'nombre' => 'Ciudad Delgado'],
            ['id_departamento' => 1, 'nombre' => 'El Paisnal'],
            ['id_departamento' => 1, 'nombre' => 'Guazapa'],
            ['id_departamento' => 1, 'nombre' => 'Ilopango'],
            ['id_departamento' => 1, 'nombre' => 'Mejicanos'],
            ['id_departamento' => 1, 'nombre' => 'Nejapa'],
            ['id_departamento' => 1, 'nombre' => 'Panchimalco'],
            ['id_departamento' => 1, 'nombre' => 'Rosario de Mora'],
            ['id_departamento' => 1, 'nombre' => 'San Marcos'],
            ['id_departamento' => 1, 'nombre' => 'San Martín'],
            ['id_departamento' => 1, 'nombre' => 'Santiago Texacuangos'],
            ['id_departamento' => 1, 'nombre' => 'Santo Tomás'],
            ['id_departamento' => 1, 'nombre' => 'Soyapango'],
            ['id_departamento' => 1, 'nombre' => 'Tonacatepeque'],

            // ID 2: La Libertad
            ['id_departamento' => 2, 'nombre' => 'Santa Tecla'],
            ['id_departamento' => 2, 'nombre' => 'Antiguo Cuscatlán'],
            ['id_departamento' => 2, 'nombre' => 'Chiltiupán'],
            ['id_departamento' => 2, 'nombre' => 'Ciudad Arce'],
            ['id_departamento' => 2, 'nombre' => 'Colón'],
            ['id_departamento' => 2, 'nombre' => 'Comasagua'],
            ['id_departamento' => 2, 'nombre' => 'Huizúcar'],
            ['id_departamento' => 2, 'nombre' => 'Jayaque'],
            ['id_departamento' => 2, 'nombre' => 'Jicalapa'],
            ['id_departamento' => 2, 'nombre' => 'La Libertad'],
            ['id_departamento' => 2, 'nombre' => 'Nuevo Cuscatlán'],
            ['id_departamento' => 2, 'nombre' => 'Quezaltepeque'],
            ['id_departamento' => 2, 'nombre' => 'Sacacoyo'],
            ['id_departamento' => 2, 'nombre' => 'San José Villanueva'],
            ['id_departamento' => 2, 'nombre' => 'San Juan Opico'],
            ['id_departamento' => 2, 'nombre' => 'San Matías'],
            ['id_departamento' => 2, 'nombre' => 'San Pablo Tacachico'],
            ['id_departamento' => 2, 'nombre' => 'Talnique'],
            ['id_departamento' => 2, 'nombre' => 'Tamanique'],
            ['id_departamento' => 2, 'nombre' => 'Teotepeque'],
            ['id_departamento' => 2, 'nombre' => 'Tepecoyo'],
            ['id_departamento' => 2, 'nombre' => 'Zaragoza'],

            // ID 3: Santa Ana
            ['id_departamento' => 3, 'nombre' => 'Santa Ana'],
            ['id_departamento' => 3, 'nombre' => 'Candelaria de la Frontera'],
            ['id_departamento' => 3, 'nombre' => 'Chalchuapa'],
            ['id_departamento' => 3, 'nombre' => 'Coatepeque'],
            ['id_departamento' => 3, 'nombre' => 'El Congo'],
            ['id_departamento' => 3, 'nombre' => 'El Porvenir'],
            ['id_departamento' => 3, 'nombre' => 'Masahuat'],
            ['id_departamento' => 3, 'nombre' => 'Metapán'],
            ['id_departamento' => 3, 'nombre' => 'San Antonio Pajonal'],
            ['id_departamento' => 3, 'nombre' => 'San Sebastián Salitrillo'],
            ['id_departamento' => 3, 'nombre' => 'Santa Rosa Guachipilín'],
            ['id_departamento' => 3, 'nombre' => 'Santiago de la Frontera'],
            ['id_departamento' => 3, 'nombre' => 'Texistepeque'],

            // ID 4: San Miguel
            ['id_departamento' => 4, 'nombre' => 'San Miguel'],
            ['id_departamento' => 4, 'nombre' => 'Carolina'],
            ['id_departamento' => 4, 'nombre' => 'Chapeltique'],
            ['id_departamento' => 4, 'nombre' => 'Chinameca'],
            ['id_departamento' => 4, 'nombre' => 'Chirilagua'],
            ['id_departamento' => 4, 'nombre' => 'Ciudad Barrios'],
            ['id_departamento' => 4, 'nombre' => 'Comacarán'],
            ['id_departamento' => 4, 'nombre' => 'El Tránsito'],
            ['id_departamento' => 4, 'nombre' => 'Lolotique'],
            ['id_departamento' => 4, 'nombre' => 'Moncagua'],
            ['id_departamento' => 4, 'nombre' => 'Nueva Guadalupe'],
            ['id_departamento' => 4, 'nombre' => 'Nuevo Edén de San Juan'],
            ['id_departamento' => 4, 'nombre' => 'Quelepa'],
            ['id_departamento' => 4, 'nombre' => 'San Antonio del Mosco'],
            ['id_departamento' => 4, 'nombre' => 'San Gerardo'],
            ['id_departamento' => 4, 'nombre' => 'San Jorge'],
            ['id_departamento' => 4, 'nombre' => 'San Luis de la Reina'],
            ['id_departamento' => 4, 'nombre' => 'San Rafael Oriente'],
            ['id_departamento' => 4, 'nombre' => 'Sesori'],
            ['id_departamento' => 4, 'nombre' => 'Uluazapa'],

            // ID 5: La Unión
            ['id_departamento' => 5, 'nombre' => 'La Unión'],
            ['id_departamento' => 5, 'nombre' => 'Anamorós'],
            ['id_departamento' => 5, 'nombre' => 'Bolívar'],
            ['id_departamento' => 5, 'nombre' => 'Concepción de Oriente'],
            ['id_departamento' => 5, 'nombre' => 'Conchagua'],
            ['id_departamento' => 5, 'nombre' => 'El Carmen'],
            ['id_departamento' => 5, 'nombre' => 'El Sauce'],
            ['id_departamento' => 5, 'nombre' => 'Intipucá'],
            ['id_departamento' => 5, 'nombre' => 'Lislique'],
            ['id_departamento' => 5, 'nombre' => 'Meanguera del Golfo'],
            ['id_departamento' => 5, 'nombre' => 'Nueva Esparta'],
            ['id_departamento' => 5, 'nombre' => 'Pasaquina'],
            ['id_departamento' => 5, 'nombre' => 'Polorós'],
            ['id_departamento' => 5, 'nombre' => 'San Alejo'],
            ['id_departamento' => 5, 'nombre' => 'San José'],
            ['id_departamento' => 5, 'nombre' => 'Santa Rosa de Lima'],
            ['id_departamento' => 5, 'nombre' => 'Yayantique'],
            ['id_departamento' => 5, 'nombre' => 'Yucuaiquín'],

            // ID 6: Sonsonate
            ['id_departamento' => 6, 'nombre' => 'Sonsonate'],
            ['id_departamento' => 6, 'nombre' => 'Acajutla'],
            ['id_departamento' => 6, 'nombre' => 'Armenia'],
            ['id_departamento' => 6, 'nombre' => 'Caluco'],
            ['id_departamento' => 6, 'nombre' => 'Cuisnahuat'],
            ['id_departamento' => 6, 'nombre' => 'Izalco'],
            ['id_departamento' => 6, 'nombre' => 'Juayúa'],
            ['id_departamento' => 6, 'nombre' => 'Nahuizalco'],
            ['id_departamento' => 6, 'nombre' => 'Nahulingo'],
            ['id_departamento' => 6, 'nombre' => 'Salcoatitán'],
            ['id_departamento' => 6, 'nombre' => 'San Antonio del Monte'],
            ['id_departamento' => 6, 'nombre' => 'San Julián'],
            ['id_departamento' => 6, 'nombre' => 'Santa Catarina Masahuat'],
            ['id_departamento' => 6, 'nombre' => 'Santa Isabel Ishuatán'],
            ['id_departamento' => 6, 'nombre' => 'Santo Domingo de Guzmán'],
            ['id_departamento' => 6, 'nombre' => 'Sonzacate'],

            // ID 7: Ahuachapán
            ['id_departamento' => 7, 'nombre' => 'Ahuachapán'],
            ['id_departamento' => 7, 'nombre' => 'Apaneca'],
            ['id_departamento' => 7, 'nombre' => 'Atiquizaya'],
            ['id_departamento' => 7, 'nombre' => 'Concepción de Ataco'],
            ['id_departamento' => 7, 'nombre' => 'El Refugio'],
            ['id_departamento' => 7, 'nombre' => 'Guaymango'],
            ['id_departamento' => 7, 'nombre' => 'Jujutla'],
            ['id_departamento' => 7, 'nombre' => 'San Francisco Menéndez'],
            ['id_departamento' => 7, 'nombre' => 'San Lorenzo'],
            ['id_departamento' => 7, 'nombre' => 'San Pedro Puxtla'],
            ['id_departamento' => 7, 'nombre' => 'Tacuba'],
            ['id_departamento' => 7, 'nombre' => 'Turín'],

            // ID 8: Cabañas
            ['id_departamento' => 8, 'nombre' => 'Sensuntepeque'],
            ['id_departamento' => 8, 'nombre' => 'Cinquera'],
            ['id_departamento' => 8, 'nombre' => 'Dolores'],
            ['id_departamento' => 8, 'nombre' => 'Guacotecti'],
            ['id_departamento' => 8, 'nombre' => 'Ilobasco'],
            ['id_departamento' => 8, 'nombre' => 'Jutiapa'],
            ['id_departamento' => 8, 'nombre' => 'San Isidro'],
            ['id_departamento' => 8, 'nombre' => 'Tejutepeque'],
            ['id_departamento' => 8, 'nombre' => 'Victoria'],

            // ID 9: Chalatenango
            ['id_departamento' => 9, 'nombre' => 'Chalatenango'],
            ['id_departamento' => 9, 'nombre' => 'Agua Caliente'],
            ['id_departamento' => 9, 'nombre' => 'Arcatao'],
            ['id_departamento' => 9, 'nombre' => 'Azacualpa'],
            ['id_departamento' => 9, 'nombre' => 'Cancasque'],
            ['id_departamento' => 9, 'nombre' => 'Citalá'],
            ['id_departamento' => 9, 'nombre' => 'Comalapa'],
            ['id_departamento' => 9, 'nombre' => 'Concepción Quezaltepeque'],
            ['id_departamento' => 9, 'nombre' => 'Dulce Nombre de María'],
            ['id_departamento' => 9, 'nombre' => 'El Carrizal'],
            ['id_departamento' => 9, 'nombre' => 'El Paraíso'],
            ['id_departamento' => 9, 'nombre' => 'La Laguna'],
            ['id_departamento' => 9, 'nombre' => 'La Palma'],
            ['id_departamento' => 9, 'nombre' => 'La Reina'],
            ['id_departamento' => 9, 'nombre' => 'Las Flores'],
            ['id_departamento' => 9, 'nombre' => 'Las Vueltas'],
            ['id_departamento' => 9, 'nombre' => 'Nombre de Jesús'],
            ['id_departamento' => 9, 'nombre' => 'Nueva Concepción'],
            ['id_departamento' => 9, 'nombre' => 'Nueva Trinidad'],
            ['id_departamento' => 9, 'nombre' => 'Ojos de Agua'],
            ['id_departamento' => 9, 'nombre' => 'Potonico'],
            ['id_departamento' => 9, 'nombre' => 'San Antonio de la Cruz'],
            ['id_departamento' => 9, 'nombre' => 'San Antonio Los Ranchos'],
            ['id_departamento' => 9, 'nombre' => 'San Fernando'],
            ['id_departamento' => 9, 'nombre' => 'San Francisco Lempa'],
            ['id_departamento' => 9, 'nombre' => 'San Francisco Morazán'],
            ['id_departamento' => 9, 'nombre' => 'San Ignacio'],
            ['id_departamento' => 9, 'nombre' => 'San Isidro Labrador'],
            ['id_departamento' => 9, 'nombre' => 'San José Cancasque'], // A veces repetido como Cancasque
            ['id_departamento' => 9, 'nombre' => 'San José Las Flores'], // A veces repetido como Las Flores
            ['id_departamento' => 9, 'nombre' => 'San Luis del Carmen'],
            ['id_departamento' => 9, 'nombre' => 'San Miguel de Mercedes'],
            ['id_departamento' => 9, 'nombre' => 'San Rafael'],
            ['id_departamento' => 9, 'nombre' => 'Santa Rita'],
            ['id_departamento' => 9, 'nombre' => 'Tejutla'],

            // ID 10: Cuscatlán
            ['id_departamento' => 10, 'nombre' => 'Cojutepeque'],
            ['id_departamento' => 10, 'nombre' => 'Candelaria'],
            ['id_departamento' => 10, 'nombre' => 'El Carmen'],
            ['id_departamento' => 10, 'nombre' => 'El Rosario'],
            ['id_departamento' => 10, 'nombre' => 'Monte San Juan'],
            ['id_departamento' => 10, 'nombre' => 'Oratorio de Concepción'],
            ['id_departamento' => 10, 'nombre' => 'San Bartolomé Perulapía'],
            ['id_departamento' => 10, 'nombre' => 'San Cristóbal'],
            ['id_departamento' => 10, 'nombre' => 'San José Guayabal'],
            ['id_departamento' => 10, 'nombre' => 'San Pedro Perulapán'],
            ['id_departamento' => 10, 'nombre' => 'San Rafael Cedros'],
            ['id_departamento' => 10, 'nombre' => 'San Ramón'],
            ['id_departamento' => 10, 'nombre' => 'Santa Cruz Analquito'],
            ['id_departamento' => 10, 'nombre' => 'Santa Cruz Michapa'],
            ['id_departamento' => 10, 'nombre' => 'Suchitoto'],
            ['id_departamento' => 10, 'nombre' => 'Tenancingo'],

            // ID 11: Morazán
            ['id_departamento' => 11, 'nombre' => 'San Francisco Gotera'],
            ['id_departamento' => 11, 'nombre' => 'Arambala'],
            ['id_departamento' => 11, 'nombre' => 'Cacaopera'],
            ['id_departamento' => 11, 'nombre' => 'Chilanga'],
            ['id_departamento' => 11, 'nombre' => 'Corinto'],
            ['id_departamento' => 11, 'nombre' => 'Delicias de Concepción'],
            ['id_departamento' => 11, 'nombre' => 'El Divisadero'],
            ['id_departamento' => 11, 'nombre' => 'El Rosario'],
            ['id_departamento' => 11, 'nombre' => 'Gualococti'],
            ['id_departamento' => 11, 'nombre' => 'Guatajiagua'],
            ['id_departamento' => 11, 'nombre' => 'Joateca'],
            ['id_departamento' => 11, 'nombre' => 'Jocoaitique'],
            ['id_departamento' => 11, 'nombre' => 'Jocoro'],
            ['id_departamento' => 11, 'nombre' => 'Lolotiquillo'],
            ['id_departamento' => 11, 'nombre' => 'Meanguera'],
            ['id_departamento' => 11, 'nombre' => 'Osicala'],
            ['id_departamento' => 11, 'nombre' => 'Perquín'],
            ['id_departamento' => 11, 'nombre' => 'San Carlos'],
            ['id_departamento' => 11, 'nombre' => 'San Fernando'],
            ['id_departamento' => 11, 'nombre' => 'San Isidro'],
            ['id_departamento' => 11, 'nombre' => 'San Simón'],
            ['id_departamento' => 11, 'nombre' => 'Sensembra'],
            ['id_departamento' => 11, 'nombre' => 'Sociedad'],
            ['id_departamento' => 11, 'nombre' => 'Torola'],
            ['id_departamento' => 11, 'nombre' => 'Yamabal'],
            ['id_departamento' => 11, 'nombre' => 'Yoloaiquín'],

            // ID 12: La Paz
            ['id_departamento' => 12, 'nombre' => 'Zacatecoluca'],
            ['id_departamento' => 12, 'nombre' => 'Cuyultitán'],
            ['id_departamento' => 12, 'nombre' => 'El Rosario'],
            ['id_departamento' => 12, 'nombre' => 'Jerusalén'],
            ['id_departamento' => 12, 'nombre' => 'Mercedes La Ceiba'],
            ['id_departamento' => 12, 'nombre' => 'Olocuilta'],
            ['id_departamento' => 12, 'nombre' => 'Paraíso de Osorio'],
            ['id_departamento' => 12, 'nombre' => 'San Antonio Masahuat'],
            ['id_departamento' => 12, 'nombre' => 'San Emigdio'],
            ['id_departamento' => 12, 'nombre' => 'San Francisco Chinameca'],
            ['id_departamento' => 12, 'nombre' => 'San Juan Nonualco'],
            ['id_departamento' => 12, 'nombre' => 'San Juan Talpa'],
            ['id_departamento' => 12, 'nombre' => 'San Juan Tepezontes'],
            ['id_departamento' => 12, 'nombre' => 'San Luis La Herradura'],
            ['id_departamento' => 12, 'nombre' => 'San Luis Talpa'],
            ['id_departamento' => 12, 'nombre' => 'San Miguel Tepezontes'],
            ['id_departamento' => 12, 'nombre' => 'San Pedro Masahuat'],
            ['id_departamento' => 12, 'nombre' => 'San Pedro Nonualco'],
            ['id_departamento' => 12, 'nombre' => 'Santa María Ostuma'],
            ['id_departamento' => 12, 'nombre' => 'Santiago Nonualco'],
            ['id_departamento' => 12, 'nombre' => 'Tapalhuaca'],

            // ID 13: San Vicente
            ['id_departamento' => 13, 'nombre' => 'San Vicente'],
            ['id_departamento' => 13, 'nombre' => 'Apastepeque'],
            ['id_departamento' => 13, 'nombre' => 'Guadalupe'],
            ['id_departamento' => 13, 'nombre' => 'San Cayetano Istepeque'],
            ['id_departamento' => 13, 'nombre' => 'San Esteban Catarina'],
            ['id_departamento' => 13, 'nombre' => 'San Ildefonso'],
            ['id_departamento' => 13, 'nombre' => 'San Lorenzo'],
            ['id_departamento' => 13, 'nombre' => 'San Sebastián'],
            ['id_departamento' => 13, 'nombre' => 'Santa Clara'],
            ['id_departamento' => 13, 'nombre' => 'Santo Domingo'],
            ['id_departamento' => 13, 'nombre' => 'Tecoluca'],
            ['id_departamento' => 13, 'nombre' => 'Tepetitán'],
            ['id_departamento' => 13, 'nombre' => 'Verapaz'],

            // ID 14: Usulután
            ['id_departamento' => 14, 'nombre' => 'Usulután'],
            ['id_departamento' => 14, 'nombre' => 'Alegría'],
            ['id_departamento' => 14, 'nombre' => 'Berlín'],
            ['id_departamento' => 14, 'nombre' => 'California'],
            ['id_departamento' => 14, 'nombre' => 'Concepción Batres'],
            ['id_departamento' => 14, 'nombre' => 'El Triunfo'],
            ['id_departamento' => 14, 'nombre' => 'Ereguayquín'],
            ['id_departamento' => 14, 'nombre' => 'Estanzuelas'],
            ['id_departamento' => 14, 'nombre' => 'Jiquilisco'],
            ['id_departamento' => 14, 'nombre' => 'Jucuapa'],
            ['id_departamento' => 14, 'nombre' => 'Jucuarán'],
            ['id_departamento' => 14, 'nombre' => 'Mercedes Umaña'],
            ['id_departamento' => 14, 'nombre' => 'Nueva Granada'],
            ['id_departamento' => 14, 'nombre' => 'Ozatlán'],
            ['id_departamento' => 14, 'nombre' => 'Puerto El Triunfo'],
            ['id_departamento' => 14, 'nombre' => 'San Agustín'],
            ['id_departamento' => 14, 'nombre' => 'San Buenaventura'],
            ['id_departamento' => 14, 'nombre' => 'San Dionisio'],
            ['id_departamento' => 14, 'nombre' => 'San Francisco Javier'],
            ['id_departamento' => 14, 'nombre' => 'Santa Elena'],
            ['id_departamento' => 14, 'nombre' => 'Santa María'],
            ['id_departamento' => 14, 'nombre' => 'Santiago de María'],
            ['id_departamento' => 14, 'nombre' => 'Tecapán'],
        ];
        // Para asegurar que no de error por tamaño, usamos chunk
        $chunks = array_chunk($municipios, 100);

        // Laravel permite insertar arrays de arrays directamente, mucho más rápido que un foreach con create
        foreach ($chunks as $chunk) {
            Municipio::insert($chunk);
        }
    }
}
